package org.test.seven_twenty.utility.in_a_row_counter;

import java.io.File;
import java.io.FileNotFoundException;

final class TestDirHandler {
    private static final String testDirName = "tests-output-files";

    /** For organisational purposes any files generated by the tests are stored in their own folder this method handles
     *  the creation of that folder.
     *  @return A File representation of the test folder if it exists or was created.
     *  @throws FileNotFoundException If it was failed to be created.**/
    static File setupTestDir() throws FileNotFoundException {
        final var testDir = new File(testDirName);
        if(!testDir.exists() && !testDir.mkdir()) {
            throw new FileNotFoundException(
                String.format("Failed to create the \"%s\" directory required to store the output file.", testDirName)
            );
        }
        return testDir;
    }
}